### ISSUE TITLE
NPM package contains extra files

### ISSUE THREAD

**Issue by nikolay-borzov** [es-shims/Array.prototype.flat#12]
`.github`, `test`, `.editorconfig`, `.eslintrc`, `.nycrc`, `.travis.yml`

**Comment by ljharb** [comment]
None of these are extra (except perhaps `.github` and `.travis.yml`) as they're all required for `npm explore foo && npm install && npm test` to work.

Excluding `.github` and `.travis.yml` would be fine, but it would be of such negligible size that I fail to see the value versus having to have an `.npmignore` file.
