### ISSUE TITLE
Incorrectly eats React nodes in jest tests

### ISSUE THREAD

**Issue by ericbf** [es-shims/Array.prototype.flat#5]
`console.log([<span>Hello</span>].flat(Infinity))` outputs `[]` when using this shim in tests, but it should output `[{ $type...etc }]`.

It seems to eat the react (jsx) element.

**Comment by ericbf** [comment]
This is on node version v10.16.3 and npm version 6.11.3

**Comment by ljharb** [comment]
I agree that a jsx element - a non-array object - should not be flattened.

However, I can't reproduce this with the native `.flat` or with this package, in node 10 or 12.

Are you sure you're not doing some kind of mocking in your jest config? Could you provide a repro repo?

**Comment by ericbf** [comment]
With dependencies:

```json
{
	"array.prototype.flat": "^1.2.2",
	"react": "^16.10.2"
}
```

When I run this in node:

```js
const React = require("react")

Array.prototype.flat = require("array.prototype.flat")

console.log([React.createElement("span", { children: "Hello!" })].flat(Infinity))
```

The output is `[]`.

However if I run the same console line in the browser with the builtin version, I get the expected `[{...}]`.

**Comment by ljharb** [comment]
Please do not ever directly assign to `Array.prototype`. If you want to shim it (install it in the envionment), use the method explicitly designed for that:
```js
require('array.prototype.flat/auto');
```
or the other mechanisms in the readme.

Can you console log the array before flattening as well, to be sure that the output is what you expect?

**Comment by ericbf** [comment]
Yes, after I left home this morning I thought I should have included that too. I'll add that when I get home.

**Comment by ericbf** [comment]
So funny story – it was actually the prototype assignment assignment that was causing it. When using the `auto` like you suggested, it works fine:

```jsx
const React = require("react")

Object.defineProperty(Array.prototype, "flat", {
	value: require("array.prototype.flat"),
	configurable: false,
	enumerable: false
})

const span = React.createElement("span", { children: "Hello!" })

console.log([span])
console.log([span].flat(Infinity))
```

Output:
```js
[ { '$$typeof': Symbol(react.element),
    type: 'span',
    key: null,
    ref: null,
    props: { children: 'Hello!' },
    _owner: null,
    _store: {} } ]
[]
```

Versus

```jsx
const React = require("react")

require("array.prototype.flat/auto")

const span = React.createElement("span", { children: "Hello!" })

console.log([span])
console.log([span].flat(Infinity))
```

Output:
```js
[ { '$$typeof': Symbol(react.element),
    type: 'span',
    key: null,
    ref: null,
    props: { children: 'Hello!' },
    _owner: null,
    _store: {} } ]
[ { '$$typeof': Symbol(react.element),
    type: 'span',
    key: null,
    ref: null,
    props: { children: 'Hello!' },
    _owner: null,
    _store: {} } ]
```
