### ISSUE TITLE
Backwards compatibility: v1.2.3 seems to use es-abstract@1.17.0-next.1

### ISSUE THREAD

**Issue by oliverseal** [es-shims/Array.prototype.flat#7]
It seems the latest version is referencing `es-abstract@1.17.0-next.1` which I think may have some backwards compatibility issues.
Seeing things like:
```
Test suite failed to run

    Cannot find module 'es-abstract/2019/ArraySpeciesCreate' from 'implementation.js'

      at Resolver.resolveModule (../home/devusr/node_modules/jest-resolve/build/index.js:221:17)
      at Object.<anonymous> (../home/devusr/node_modules/array.prototype.flat/implementation.js:3:26)
```

It's possible it could be something in our dependency try that I'm confusing. I guess I'm looking to make sure the use of `es-abstract@1.17.0-next.1` in the current release is intentional.

**Comment by ljharb** [comment]
It’s definitely intentional, and tests pass. Since the error is in jest-resolve, is there a chance your jest config is mocking out es-abstract somehow?

**Comment by oliverseal** [comment]
Thanks!
Still investigating the pathing on our side here. I'll close this issue given that using that version is intentional.

**Comment by ljharb** [comment]
Happy to reopen if there's something actionable for me to fix.

**Comment by oliverseal** [comment]
Looks like, for us, this was related to https://github.com/ljharb/es-abstract/issues/84
We fixed by locking nested dev dependency versions.

**Comment by ljharb** [comment]
That isn’t a fix; all that’s doing is working around a webpack bug by preventing yourself from getting any future bug fixes.

**Comment by oliverseal** [comment]
You're right. (Words matter.) It's not a fix. We are just unblocked from running our tests for the moment.
