### ISSUE TITLE
npm error installing on windows

### ISSUE THREAD

**Issue by Zhang-Yida** [es-shims/Array.prototype.flat#8]
When I run npm i array.prototype.flat -D
I got the error

npm ERR! code ENOENT
npm ERR! syscall rename
npm ERR! path C:\ProjectCode\pwc-frontend-framework\node_modules\array.prototype.flat
npm ERR! dest C:\ProjectCode\pwc-frontend-framework\node_modules\.array.prototype.flat.DELETE
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\ProjectCode\pwc-frontend-framework\node_modules\array.prototype.flat' -> 'C:\ProjectCode\pwc-frontend-framework\node_modules\.array.prototype.flat.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\meng mb zhang\AppData\Roaming\npm-cache\_logs\2019-12-19T02_08_04_234Z-debug.log

**Comment by Zhang-Yida** [comment]
node version v12.14.0
npm version v6.13.4

**Comment by ljharb** [comment]
This seems like an error with npm on windows, and has literally nothing to do with this package. Please file an issue with them.

**Comment by Zhang-Yida** [comment]
@ljharb Hello, I have try many times, and I am sure. When I run `npm i array.prototype.flat -S` on my windows pc, it is never successful. Please help me.

**Comment by ljharb** [comment]
@Zhang-Yida Please file an issue on https://github.com/npm/cli with all the relevant info (node and npm version, in particular) and be sure you try the latest version of npm and node first.

**Comment by judypan** [comment]
Hi the same issue happened to me. May I know whether you can fix it at the end? Thanks.
